### ISSUE TITLE
Amazonリンク取得処理がnullになる分岐がある

### ISSUE THREAD

**Issue by ktakahiro150397** [ktakahiro150397/RankPrediction_Web#126]
リストの初期化がされていないため、セットしている箇所以外の分岐を通るとnullになる
一旦、最初に空リストで初期化して対応

https://github.com/ktakahiro150397/RankPrediction_Web/blob/382691a58fdcf093560a0744b382f893d612af01/RankPrediction_Web/Models/PredictionResult.cs#L73

#124 #125 で本番まで対応済み

**Comment by WagashiMgmg** [comment]
あざ
