### ISSUE TITLE
マッチカウントが無いときの推定エラー

### ISSUE THREAD

**Issue by WagashiMgmg** [ktakahiro150397/RankPrediction_Web#129]
マッチカウントを入れずにモデルを作っているのに、predictionでマッチカウント-1をそのまま使ってしまいエラーが出ている。
モデル生成時の教師データの次元と、推定時のテストデータの次元が一致している必要がある。

解決法として以下が思い付く。
- prediction時にマッチカウント列をselectしない（SQLでのアプローチ）
- predictionコード内で次元を合わせる（pythonでのアプローチ）

**Comment by ktakahiro150397** [comment]
SQL側でやりま

**Comment by ktakahiro150397** [comment]
昨日やった
