### ISSUE TITLE
ランク予測結果がNULLになる

### ISSUE THREAD

**Issue by ktakahiro150397** [ktakahiro150397/RankPrediction_Web#52]
入力データ：
<img width="714" alt="スクリーンショット 2021-08-27 0 55 28" src="https://user-images.githubusercontent.com/58302085/130996712-6d2b4e7d-bc24-4ac2-9a8a-a1abbc3daf01.png">

予測結果がNULLとなっている：
<img width="466" alt="スクリーンショット 2021-08-27 0 58 27" src="https://user-images.githubusercontent.com/58302085/130996630-6f169e24-2479-473c-8b49-95f9a41341ba.png">

誰か直してくれ〜〜

**Comment by WagashiMgmg** [comment]
#59 で対策した。対策できた気がする

**Comment by ktakahiro150397** [comment]
前回エラー起こしたデータでエラー起きないのでOKですわ
