### ISSUE TITLE
広告を診断結果ごとに分ける

### ISSUE THREAD

**Issue by WagashiMgmg** [ktakahiro150397/RankPrediction_Web#74]
ブロンズなら「FPSの基本」の本
シルバーならグラボ
ゴールドならマウスパッド
...
プレデターなら高級マイク

みたいな

**Comment by WagashiMgmg** [comment]
@ktakahiro150397 のSQLテーブルにURLぶち込んだ

**Comment by WagashiMgmg** [comment]
SQLをcshtmlで読み込むところを作れなさ過ぎてむりになった

**Comment by ktakahiro150397** [comment]
DbContextとLINQでググって頑張れ！

**Comment by WagashiMgmg** [comment]
分からん過ぎて頭おかしくなる

**Comment by WagashiMgmg** [comment]
#119 です

**Comment by WagashiMgmg** [comment]
とりあえず目的達成したのでクローズ
改善要求あれば新たなissueかな
