### ISSUE TITLE
計算ストアドのタイムアウト

### ISSUE THREAD

**Issue by ktakahiro150397** [ktakahiro150397/RankPrediction_Web#93]
ローカルでも発生する

Microsoft.Data.SqlClient.SqlException (0x80131904): Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.

データ数増えてきて計算に時間がかかっているんだと思う。
タイムアウトまでに結果が返ってこないためにWeb画面では例外が発生し、エラー扱いとなる。

既定値は30秒
https://docs.microsoft.com/ja-jp/dotnet/api/system.data.idbcommand.commandtimeout?view=netframework-4.8

このエラーになるということは、計算待ち時間がめちゃめちゃに長いということになる！
ストアド側でなんとかなりません？

**Comment by ktakahiro150397** [comment]
タイムアウトを無制限にしたり伸ばしたりは可能
でもあんまり本質的な解決じゃないなっていうアレ

**Comment by WagashiMgmg** [comment]
基本ユーザーには推定のストアドプロシジャのみ実行させるか。どうせモデルを作るのに時間かかってる（たぶん）はずなので。
何日（何時間）かに一回モデルを勝手に作るようにしたい

**Comment by WagashiMgmg** [comment]
現状まとめ
- python実行は早い
- SQL SELECTも早い
- pythonのスクリプトを呼び出すまでが長い
- サーバースペックと思われている

**Comment by ktakahiro150397** [comment]
sp_execute_external_script がめちゃめちゃにCPU食べるのか分からんけどとりあえずアップグレードで解決のように見える
破産への道も見える

**Comment by ktakahiro150397** [comment]
ま、CPUで殴れば大丈夫でしょう
というわけでクローズ
